apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ticketingapi
  namespace: default
  labels:
    app: ticketingapi
spec:
  replicas: 1
  selector:
    matchLabels:
        app: ticketingapi
  template:
    metadata:
      name: ticketingapi
      labels:
        app: ticketingapi
    spec:
      containers:
      - name: ticketingapi
        image: denhamparry/ticketing.api:0.2.107-beta
        env:
        - name: ValueFromKubernetesEnvVariable
          valueFrom:
            configMapKeyRef:
              name: ticketingapi-configmap
              key: ValueFromKubernetesEnvVariable
        - name: ValueOverride
          valueFrom:
            configMapKeyRef:
              name: ticketingapi-configmap
              key: ValueOverride
        - name: ValueFromKubernetesSecret
          valueFrom:
            secretKeyRef:
              name: ticketingapi-secret
              key: ValueFromKubernetesSecret
        resources: {}
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
        securityContext:
          privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler